server {
    listen 80;
    server_name localhost;

    # Root directory for static web files
    root /usr/share/nginx/html;
    index index.html index.htm;

    # Route default web requests
    location / {
        # Fallback to index.html if the file or directory isn't found
        try_files $uri $uri/ /index.html;
    }
}