apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: restrict-mongo-user
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      app: ecom-mongo-user
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: ecom-user
    ports:
    - protocol: TCP
      port: 27017
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: restrict-mongo-product
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      app: ecom-mongo-product
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: ecom-product
    ports:
    - protocol: TCP
      port: 27017
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: restrict-mongo-order
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      app: ecom-mongo-order
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: ecom-order
    ports:
    - protocol: TCP
      port: 27017
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: restrict-mongo-cart
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      app: ecom-mongo-cart
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: ecom-cart
    ports:
    - protocol: TCP
      port: 27017
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: restrict-redis
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      app: ecom-redis
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: ecom-product
    ports:
    - protocol: TCP
      port: 6379
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: restrict-rabbitmq
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      app: ecom-rabbitmq
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: ecom-order
    ports:
    - protocol: TCP
      port: 5672
