apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecom-mongo-product-db-deployment
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount.mongo_product }}
  selector:
    matchLabels:
      app: ecom-mongo-product-db
  template:
    metadata:
      labels:
        app: ecom-mongo-product-db
    spec:
      containers:
        - name: ecom-mongo-product-db
          image: mongo:8.3-noble
          ports:
            - containerPort: {{ .Values.service.mongo_port }}

---

apiVersion: v1
kind: Service
metadata:
  name: mongo-product-db
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.mongo_port }}
      targetPort: {{ .Values.service.mongo_port }}
  selector:
    app: ecom-mongo-product-db